name: pirate_badge
version: 0.0.0
description: 
author: Kasper Peulen <kasperpeulen@gmail.com>
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  browser: '^0.10.0+2'
  angular2: '^2.0.0-alpha.37'
transformers:
- angular2:
    entry_points: web/app.dart